### PR TITLE
ADD: Content Filtering API

### PR DESCRIPTION
**Pull request by sihrc**

### CODE REVIEW

**Comment by sihrc** [comment]
Currently failing because server returns array of doubles. Not sure if change here to list or change server to single value.

**Comment by anneCarlson** [comment]
Why isn't codeship failing?

**Comment by madisonmay** [comment]
^ Good question.

**Comment by sihrc** [comment]
I fixed it

**Comment by sihrc** [comment]
@anneCarlson  the promised logic extraction is in this PR. sorry it should have been on its on

**Pull request merged**
