### PR TITLE
ADD: twitter engagement api

### PR DESCRIPTION
**Pull request by sihrc**

### CODE REVIEW

**Comment by Slater-Victoroff** [comment]
Looks good, why codeship failing?

**Comment by sihrc** [comment]
Ah, the first time I ran it, the boxes weren't up yet. And now, i think it's having an issue with the return type. will fix in a minute.

**Comment by sihrc** [comment]
Turns out lena actually NSFW.

**Comment by madisonmay** [comment]
Merge at will @sihrc.  Not super qualified to review this code, but LGTM.

**Pull request merged**
